---

- name: Install docker
  ansible.builtin.apt:
    pkg:
      - docker-compose
    update_cache: yes
    cache_valid_time: 3600

- name: Create homeassistant base dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ homeassistant_base_dir }}"
    - "{{ homeassistant_base_dir }}/config"
  
- name: Copy over docker compose file
  ansible.builtin.copy:
    src: "docker-compose.yaml"
    dest: "{{ homeassistant_base_dir }}/docker-compose.yaml"
    mode: '0755'

- name: Start homeassistant
  community.docker.docker_compose:
    project_src: "{{ homeassistant_base_dir }}"
