---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
spec:
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
        - name: jackett
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
          # latest is ok here because reasons
          image: lscr.io/linuxserver/jackett:latest
          ports:
            - containerPort: 9117
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: jackett-config
        - name: flaresolverr
          env:
            - name: LOG_LEVEL
              value: info
            - name: LOG_HTML
              value: "false"
            - name: CAPTCHA_SOLVER
              value: hcaptcha-solver
            - name: TZ
              value: "America/New_York"
          # latest is ok here because reasons
          image: ghcr.io/flaresolverr/flaresolverr:latest
          ports:
            - containerPort: 8191
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: jackett-config
          hostPath:
            path: /mnt/kube/jackett/config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jackett
  name: jackett
spec:
  ports:
    - name: web
      port: 80
      targetPort: 9117
  selector:
    app: jackett
  type: LoadBalancer
  loadBalancerIP: "172.27.10.84"
